name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.101

      - name: Cake Action
        run: sh build.sh
        env:
          STEAM: ${{ secrets.STEAM }}

      - uses: actions/upload-artifact@v2
        with:
          name: Reactor.dll
          path: Reactor/bin/Release/netstandard2.1/reobfuscated/Reactor-*.dll

      - uses: actions/upload-artifact@v2
        with:
          name: Reactor.Debugger.dll
          path: Reactor.Debugger/bin/Release/netstandard2.1/reobfuscated/Reactor.Debugger-*.dll
